// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project2.Models;

namespace Project2.Migrations
{
    [DbContext(typeof(TempleTourContext))]
    [Migration("20220323040531_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Project2.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AppointmentId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            TimeSlot = "8:00 a.m. - 9:00 a.m."
                        },
                        new
                        {
                            AppointmentId = 2,
                            TimeSlot = "9:00 a.m. - 10:00 a.m."
                        },
                        new
                        {
                            AppointmentId = 3,
                            TimeSlot = "10:00 a.m. - 11:00 a.m."
                        },
                        new
                        {
                            AppointmentId = 4,
                            TimeSlot = "11:00 a.m. - 12:00 p.m."
                        },
                        new
                        {
                            AppointmentId = 5,
                            TimeSlot = "12:00 p.m. - 1:00 p.m."
                        },
                        new
                        {
                            AppointmentId = 6,
                            TimeSlot = "1:00 p.m. - 2:00 p.m."
                        },
                        new
                        {
                            AppointmentId = 7,
                            TimeSlot = "2:00 p.m. - 3:00 p.m."
                        },
                        new
                        {
                            AppointmentId = 8,
                            TimeSlot = "3:00 p.m. - 4:00 p.m."
                        },
                        new
                        {
                            AppointmentId = 9,
                            TimeSlot = "4:00 p.m. - 5:00 p.m."
                        },
                        new
                        {
                            AppointmentId = 10,
                            TimeSlot = "5:00 p.m. - 6:00 p.m."
                        },
                        new
                        {
                            AppointmentId = 11,
                            TimeSlot = "6:00 p.m. - 7:00 p.m."
                        },
                        new
                        {
                            AppointmentId = 12,
                            TimeSlot = "7:00 p.m. - 8:00 p.m."
                        },
                        new
                        {
                            AppointmentId = 13,
                            TimeSlot = "8:00 p.m. - 9:00 p.m."
                        });
                });

            modelBuilder.Entity("Project2.Models.Tourist", b =>
                {
                    b.Property<int>("TouristId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("SizeOfGroup")
                        .HasColumnType("INTEGER");

                    b.HasKey("TouristId");

                    b.ToTable("Tourists");
                });
#pragma warning restore 612, 618
        }
    }
}
