// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project2.Models;

namespace Project2.Migrations
{
    [DbContext(typeof(TempleTourContext))]
    [Migration("20220323212001_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Project2.Models.Tourist", b =>
                {
                    b.Property<int>("TouristId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppointmentStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("SizeOfGroup")
                        .HasColumnType("INTEGER");

                    b.HasKey("TouristId");

                    b.ToTable("Tourists");

                    b.HasData(
                        new
                        {
                            TouristId = 1,
                            AppointmentStart = "2022-03-23T10:00:00",
                            EmailAddress = "test@test.com",
                            GroupName = "Awesome",
                            PhoneNumber = "555-555-1234",
                            SizeOfGroup = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
